#if defined _index_included
  #endinput
#endif

#define _index_included

#include <amxmodx>
#include <amxmisc>
#include <hamsandwich>
#include <fakemeta_util>
#include <fun>
#include <reapi>
#include <json>
#include <PersistentDataStorage>

#include <hns-match/globals>
#include <hns-match/hook>
#include <hns-match/ham>
#include <hns-match/forward>
#include <hns-match/event>
#include <hns-match/message>

#include <hns-match/user>
#include <hns-match/surrender>
#include <hns-match/afk>
#include <hns-match/hookOnOff>
#include <hns-match/captain>
#include <hns-match/hnsmenu>